[package]
name = "sigstore-tsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sigstore_tsp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
asn1 = "0.17"
self_cell = "1"
hex = "0.4"
sha2 = "0.10.8"
rand = "0.8.5"
