name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true

      - name: install uv
        run: >
          curl --no-progress-meter --location --fail
          --proto '=https' --tlsv1.2
          "https://astral.sh/uv/install.sh"
          | sh

      - name: Setup rust
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8
        with:
          components: rustfmt
          toolchain: 1.81.0

      - name: test
        run: make test INSTALL_EXTRA=test
